/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_ttcnc_ucsdk_dccctrllib_JNIClass */

#ifndef _Included_kr_co_ttcnc_ucsdk_dccctrllib_JNIClass
#define _Included_kr_co_ttcnc_ucsdk_dccctrllib_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_ttcnc_ucsdk_dccctrllib_JNIClass
 * Method:    getf53MKValue
 * Signature: ()[B
 */

JNIEXPORT jbyteArray JNICALL Java_kr_co_ttcnc_ucsdk_dccctrllib_getf53TokenIVValue
        (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_kr_co_ttcnc_ucsdk_dccctrllib_JNIClass_getf53MKValue
  (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_kr_co_ttcnc_ucsdk_dccctrllib_JNIClass_getAes192MKValue
        (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_kr_co_ttcnc_ucsdk_dccctrllib_JNIClass_getAes256MKValue
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
